[ids]
* = *

[main]

leftmeta = leftcontrol
delete = leftmeta
capslock = overload(extend, capslock)

[extend]

j = (
k = )
h = [
l = ]
u = {
i = }
, = _
o = |
. = -
7 = 8

f = =
d = ~
g = +

space = leftcontrol
